/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:fc1028f8-d091-4eb1-8c6e-3e52e56af15d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_fGu4FNmjF",
    "aws_user_pools_web_client_id": "1a6uo7bvk26mdrdatn3223efeq",
    "oauth": {}
};


export default awsmobile;
