/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:fc1028f8-d091-4eb1-8c6e-3e52e56af15d",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_fGu4FNmjF",
    "aws_user_pools_web_client_id": "1a6uo7bvk26mdrdatn3223efeq",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://ncfyc22m6feknpxhnorxdungom.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3sr66lueercllgg7vmahwntypu",
    "aws_user_files_s3_bucket": "reacttaskbucket1150526-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
